HTTP/1.1 200 OK
Server: nginx/1.18.0 (Ubuntu)
Date: Sun, 30 Jul 2023 16:28:28 GMT
Content-Type: image/jpeg
Content-Length: 81421
Last-Modified: Thu, 08 Jul 2021 22:17:29 GMT
Connection: close
ETag: "60e77979-13e0d"
Accept-Ranges: bytes

